# https://dev.to/n3wt0n/everything-you-need-to-know-about-github-actions-environments-9p7

name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: unit-test
        run: echo "Do a test here"

  deploy-dev:
    name: deploy-dev
    if: github.event_name == 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: development
      url: "http://dev.example.com/"
    steps:
      - name: Deploy
        run: echo I am deploying!

  deploy-staging:
    name: deploy-staging
    if: github.event.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    # environment:
    #   name: staging
    #   url: 'http://staging.example.com/'
    # steps:
    #   - name: Deploy
    #     run: echo I am deploying!
    environment:
      name: staging
      url: "http://cicd-example.s3-website.ap-northeast-2.amazonaws.com/staging/"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 rm s3://$BUCKET_NAME/staging/ --recursive
          aws s3 cp ./ s3://$BUCKET_NAME/staging/ --recursive  --exclude "*" --include "*.html"
        env:
          BUCKET_NAME: vntg-cicd-example

  deploy-production:
    name: deploy-production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "http://www.example.com"
    steps:
      - name: Deploy
        run: echo I am deploying!
